PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS idempotency_keys;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS budget_ledger;
DROP TABLE IF EXISTS deliveries;
DROP TABLE IF EXISTS redemption_status_history;
DROP TABLE IF EXISTS redemptions;
DROP TABLE IF EXISTS credit_ledger;
DROP TABLE IF EXISTS awards;
DROP TABLE IF EXISTS evidence_files;
DROP TABLE IF EXISTS charging_evidence;
DROP TABLE IF EXISTS commute_evidence;
DROP TABLE IF EXISTS hub_checklist_items;
DROP TABLE IF EXISTS charging_hubs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS pilot_config;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schema_migrations;
PRAGMA foreign_keys = ON;
